// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'rust_scrcpy_api.dart';
import 'rust_scrcpy_api/model.dart';
import 'rust_scrcpy_api/runtime.dart';
import 'rust_scrcpy_api/service.dart';
import 'scrcpy/control.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_FlowMonitorPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitorPtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RealSessionRuntimePtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntimePtr;



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw);

@protected FlowMonitor dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor(dynamic raw);

@protected RealSessionRuntime dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(dynamic raw);

@protected RealSessionRuntime dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(dynamic raw);

@protected RealSessionRuntime dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(dynamic raw);

@protected FlowMonitor dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor(dynamic raw);

@protected RealSessionRuntime dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected SessionRuntime dco_decode_TraitDef_SessionRuntime(dynamic raw);

@protected AndroidKeyEventAction dco_decode_android_key_event_action(dynamic raw);

@protected AndroidMotionEventAction dco_decode_android_motion_event_action(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected KeyEvent dco_decode_box_autoadd_key_event(dynamic raw);

@protected ScrollEvent dco_decode_box_autoadd_scroll_event(dynamic raw);

@protected SessionConfig dco_decode_box_autoadd_session_config(dynamic raw);

@protected SessionConfigV2 dco_decode_box_autoadd_session_config_v_2(dynamic raw);

@protected TouchEvent dco_decode_box_autoadd_touch_event(dynamic raw);

@protected DecoderMode dco_decode_decoder_mode(dynamic raw);

@protected DeviceInfo dco_decode_device_info(dynamic raw);

@protected ErrorCode dco_decode_error_code(dynamic raw);

@protected double dco_decode_f_32(dynamic raw);

@protected double dco_decode_f_64(dynamic raw);

@protected int dco_decode_i_32(dynamic raw);

@protected PlatformInt64 dco_decode_i_64(dynamic raw);

@protected KeyEvent dco_decode_key_event(dynamic raw);

@protected List<DeviceInfo> dco_decode_list_device_info(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected List<SessionEvent> dco_decode_list_session_event(dynamic raw);

@protected List<TextureFrame> dco_decode_list_texture_frame(dynamic raw);

@protected LogLevel dco_decode_log_level(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected OrientationChangeSource dco_decode_orientation_change_source(dynamic raw);

@protected OrientationMode dco_decode_orientation_mode(dynamic raw);

@protected RenderPipelineMode dco_decode_render_pipeline_mode(dynamic raw);

@protected ScrollEvent dco_decode_scroll_event(dynamic raw);

@protected SessionConfig dco_decode_session_config(dynamic raw);

@protected SessionConfigV2 dco_decode_session_config_v_2(dynamic raw);

@protected SessionEvent dco_decode_session_event(dynamic raw);

@protected SessionStats dco_decode_session_stats(dynamic raw);

@protected SystemKey dco_decode_system_key(dynamic raw);

@protected TextureFrame dco_decode_texture_frame(dynamic raw);

@protected TouchEvent dco_decode_touch_event(dynamic raw);

@protected int dco_decode_u_16(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected BigInt dco_decode_u_64(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected BigInt dco_decode_usize(dynamic raw);

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

@protected FlowMonitor sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor(SseDeserializer deserializer);

@protected RealSessionRuntime sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(SseDeserializer deserializer);

@protected RealSessionRuntime sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(SseDeserializer deserializer);

@protected RealSessionRuntime sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(SseDeserializer deserializer);

@protected FlowMonitor sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor(SseDeserializer deserializer);

@protected RealSessionRuntime sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected AndroidKeyEventAction sse_decode_android_key_event_action(SseDeserializer deserializer);

@protected AndroidMotionEventAction sse_decode_android_motion_event_action(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected KeyEvent sse_decode_box_autoadd_key_event(SseDeserializer deserializer);

@protected ScrollEvent sse_decode_box_autoadd_scroll_event(SseDeserializer deserializer);

@protected SessionConfig sse_decode_box_autoadd_session_config(SseDeserializer deserializer);

@protected SessionConfigV2 sse_decode_box_autoadd_session_config_v_2(SseDeserializer deserializer);

@protected TouchEvent sse_decode_box_autoadd_touch_event(SseDeserializer deserializer);

@protected DecoderMode sse_decode_decoder_mode(SseDeserializer deserializer);

@protected DeviceInfo sse_decode_device_info(SseDeserializer deserializer);

@protected ErrorCode sse_decode_error_code(SseDeserializer deserializer);

@protected double sse_decode_f_32(SseDeserializer deserializer);

@protected double sse_decode_f_64(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

@protected KeyEvent sse_decode_key_event(SseDeserializer deserializer);

@protected List<DeviceInfo> sse_decode_list_device_info(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<SessionEvent> sse_decode_list_session_event(SseDeserializer deserializer);

@protected List<TextureFrame> sse_decode_list_texture_frame(SseDeserializer deserializer);

@protected LogLevel sse_decode_log_level(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected OrientationChangeSource sse_decode_orientation_change_source(SseDeserializer deserializer);

@protected OrientationMode sse_decode_orientation_mode(SseDeserializer deserializer);

@protected RenderPipelineMode sse_decode_render_pipeline_mode(SseDeserializer deserializer);

@protected ScrollEvent sse_decode_scroll_event(SseDeserializer deserializer);

@protected SessionConfig sse_decode_session_config(SseDeserializer deserializer);

@protected SessionConfigV2 sse_decode_session_config_v_2(SseDeserializer deserializer);

@protected SessionEvent sse_decode_session_event(SseDeserializer deserializer);

@protected SessionStats sse_decode_session_stats(SseDeserializer deserializer);

@protected SystemKey sse_decode_system_key(SseDeserializer deserializer);

@protected TextureFrame sse_decode_texture_frame(SseDeserializer deserializer);

@protected TouchEvent sse_decode_touch_event(SseDeserializer deserializer);

@protected int sse_decode_u_16(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected BigInt sse_decode_usize(SseDeserializer deserializer);

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor(FlowMonitor self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(RealSessionRuntime self, SseSerializer serializer);

@protected void sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(RealSessionRuntime self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(RealSessionRuntime self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor(FlowMonitor self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(RealSessionRuntime self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_android_key_event_action(AndroidKeyEventAction self, SseSerializer serializer);

@protected void sse_encode_android_motion_event_action(AndroidMotionEventAction self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_key_event(KeyEvent self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_scroll_event(ScrollEvent self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_session_config(SessionConfig self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_session_config_v_2(SessionConfigV2 self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_touch_event(TouchEvent self, SseSerializer serializer);

@protected void sse_encode_decoder_mode(DecoderMode self, SseSerializer serializer);

@protected void sse_encode_device_info(DeviceInfo self, SseSerializer serializer);

@protected void sse_encode_error_code(ErrorCode self, SseSerializer serializer);

@protected void sse_encode_f_32(double self, SseSerializer serializer);

@protected void sse_encode_f_64(double self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_key_event(KeyEvent self, SseSerializer serializer);

@protected void sse_encode_list_device_info(List<DeviceInfo> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_list_session_event(List<SessionEvent> self, SseSerializer serializer);

@protected void sse_encode_list_texture_frame(List<TextureFrame> self, SseSerializer serializer);

@protected void sse_encode_log_level(LogLevel self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_orientation_change_source(OrientationChangeSource self, SseSerializer serializer);

@protected void sse_encode_orientation_mode(OrientationMode self, SseSerializer serializer);

@protected void sse_encode_render_pipeline_mode(RenderPipelineMode self, SseSerializer serializer);

@protected void sse_encode_scroll_event(ScrollEvent self, SseSerializer serializer);

@protected void sse_encode_session_config(SessionConfig self, SseSerializer serializer);

@protected void sse_encode_session_config_v_2(SessionConfigV2 self, SseSerializer serializer);

@protected void sse_encode_session_event(SessionEvent self, SseSerializer serializer);

@protected void sse_encode_session_stats(SessionStats self, SseSerializer serializer);

@protected void sse_encode_system_key(SystemKey self, SseSerializer serializer);

@protected void sse_encode_texture_frame(TextureFrame self, SseSerializer serializer);

@protected void sse_encode_touch_event(TouchEvent self, SseSerializer serializer);

@protected void sse_encode_u_16(int self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_usize(BigInt self, SseSerializer serializer);
                }
                


// Section: wire_class


        class RustLibWire implements BaseWire {

            factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
              RustLibWire(lib.ffiDynamicLibrary);
        
            /// Holds the symbol lookup function.
            final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                _lookup;
  
            /// The symbols are looked up in [dynamicLibrary].
            RustLibWire(ffi.DynamicLibrary dynamicLibrary)
                : _lookup = dynamicLibrary.lookup;

            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitorPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_sw_game_helper_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitorPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitorPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_sw_game_helper_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitor = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlowMonitorPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntimePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_sw_game_helper_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntimePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntimePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_sw_game_helper_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntime = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRealSessionRuntimePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
        }
        