// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'gh_api/flutter_api.dart';
import 'gh_common/model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    
                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.11.1';

                  @override
                  int get rustContentHash => -2103028118;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'rust_scrcpy',
                    ioDirectory: '../rust-ws-scrcpy/target/release/',
                    webPrefix: 'pkg/',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  Future<String> crateGhApiFlutterApiCreateSession({required SessionConfig config });

Future<String> crateGhApiFlutterApiCreateSessionV2({required SessionConfigV2 config });

Future<void> crateGhApiFlutterApiDisposeSession({required String sessionId });

Future<DeviceInfo> crateGhApiFlutterApiGetDeviceInfo({required String adbPath , required String deviceId });

Future<SessionStats> crateGhApiFlutterApiGetSessionStats({required String sessionId });

Future<List<DeviceInfo>> crateGhApiFlutterApiListDevices({required String adbPath });

Future<void> crateGhApiFlutterApiRequestIdr({required String sessionId });

Future<void> crateGhApiFlutterApiSendKey({required String sessionId , required KeyEvent event });

Future<void> crateGhApiFlutterApiSendScroll({required String sessionId , required ScrollEvent event });

Future<void> crateGhApiFlutterApiSendSystemKey({required String sessionId , required SystemKey key });

Future<void> crateGhApiFlutterApiSendText({required String sessionId , required String text });

Future<void> crateGhApiFlutterApiSendTouch({required String sessionId , required TouchEvent event });

Future<void> crateGhApiFlutterApiSetClipboard({required String sessionId , required String text , required bool paste });

Future<void> crateGhApiFlutterApiSetOrientationMode({required String sessionId , required OrientationMode mode });

Future<void> crateGhApiFlutterApiSetupLogger({required LogLevel maxLevel });

Future<void> crateGhApiFlutterApiStartSession({required String sessionId });

Future<void> crateGhApiFlutterApiStopSession({required String sessionId });

Stream<String> crateGhApiFlutterApiSubscribeClipboardEvents({required String sessionId });

Stream<LogEvent> crateGhApiFlutterApiSubscribeLogs();

Stream<SessionEvent> crateGhApiFlutterApiSubscribeSessionEvents({required String sessionId });


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Future<String> crateGhApiFlutterApiCreateSession({required SessionConfig config })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_box_autoadd_session_config(config, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiCreateSessionConstMeta,
            argValues: [config],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiCreateSessionConstMeta => const TaskConstMeta(
            debugName: "create_session",
            argNames: ["config"],
        );
        

@override Future<String> crateGhApiFlutterApiCreateSessionV2({required SessionConfigV2 config })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_box_autoadd_session_config_v_2(config, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiCreateSessionV2ConstMeta,
            argValues: [config],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiCreateSessionV2ConstMeta => const TaskConstMeta(
            debugName: "create_session_v2",
            argNames: ["config"],
        );
        

@override Future<void> crateGhApiFlutterApiDisposeSession({required String sessionId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiDisposeSessionConstMeta,
            argValues: [sessionId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiDisposeSessionConstMeta => const TaskConstMeta(
            debugName: "dispose_session",
            argNames: ["sessionId"],
        );
        

@override Future<DeviceInfo> crateGhApiFlutterApiGetDeviceInfo({required String adbPath , required String deviceId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(adbPath, serializer);
sse_encode_String(deviceId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_device_info,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiGetDeviceInfoConstMeta,
            argValues: [adbPath, deviceId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiGetDeviceInfoConstMeta => const TaskConstMeta(
            debugName: "get_device_info",
            argNames: ["adbPath", "deviceId"],
        );
        

@override Future<SessionStats> crateGhApiFlutterApiGetSessionStats({required String sessionId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_session_stats,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiGetSessionStatsConstMeta,
            argValues: [sessionId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiGetSessionStatsConstMeta => const TaskConstMeta(
            debugName: "get_session_stats",
            argNames: ["sessionId"],
        );
        

@override Future<List<DeviceInfo>> crateGhApiFlutterApiListDevices({required String adbPath })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(adbPath, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_device_info,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiListDevicesConstMeta,
            argValues: [adbPath],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiListDevicesConstMeta => const TaskConstMeta(
            debugName: "list_devices",
            argNames: ["adbPath"],
        );
        

@override Future<void> crateGhApiFlutterApiRequestIdr({required String sessionId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiRequestIdrConstMeta,
            argValues: [sessionId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiRequestIdrConstMeta => const TaskConstMeta(
            debugName: "request_idr",
            argNames: ["sessionId"],
        );
        

@override Future<void> crateGhApiFlutterApiSendKey({required String sessionId , required KeyEvent event })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
sse_encode_box_autoadd_key_event(event, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSendKeyConstMeta,
            argValues: [sessionId, event],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiSendKeyConstMeta => const TaskConstMeta(
            debugName: "send_key",
            argNames: ["sessionId", "event"],
        );
        

@override Future<void> crateGhApiFlutterApiSendScroll({required String sessionId , required ScrollEvent event })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
sse_encode_box_autoadd_scroll_event(event, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSendScrollConstMeta,
            argValues: [sessionId, event],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiSendScrollConstMeta => const TaskConstMeta(
            debugName: "send_scroll",
            argNames: ["sessionId", "event"],
        );
        

@override Future<void> crateGhApiFlutterApiSendSystemKey({required String sessionId , required SystemKey key })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
sse_encode_system_key(key, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSendSystemKeyConstMeta,
            argValues: [sessionId, key],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiSendSystemKeyConstMeta => const TaskConstMeta(
            debugName: "send_system_key",
            argNames: ["sessionId", "key"],
        );
        

@override Future<void> crateGhApiFlutterApiSendText({required String sessionId , required String text })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
sse_encode_String(text, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSendTextConstMeta,
            argValues: [sessionId, text],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiSendTextConstMeta => const TaskConstMeta(
            debugName: "send_text",
            argNames: ["sessionId", "text"],
        );
        

@override Future<void> crateGhApiFlutterApiSendTouch({required String sessionId , required TouchEvent event })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
sse_encode_box_autoadd_touch_event(event, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSendTouchConstMeta,
            argValues: [sessionId, event],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiSendTouchConstMeta => const TaskConstMeta(
            debugName: "send_touch",
            argNames: ["sessionId", "event"],
        );
        

@override Future<void> crateGhApiFlutterApiSetClipboard({required String sessionId , required String text , required bool paste })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
sse_encode_String(text, serializer);
sse_encode_bool(paste, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSetClipboardConstMeta,
            argValues: [sessionId, text, paste],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiSetClipboardConstMeta => const TaskConstMeta(
            debugName: "set_clipboard",
            argNames: ["sessionId", "text", "paste"],
        );
        

@override Future<void> crateGhApiFlutterApiSetOrientationMode({required String sessionId , required OrientationMode mode })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
sse_encode_orientation_mode(mode, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSetOrientationModeConstMeta,
            argValues: [sessionId, mode],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiSetOrientationModeConstMeta => const TaskConstMeta(
            debugName: "set_orientation_mode",
            argNames: ["sessionId", "mode"],
        );
        

@override Future<void> crateGhApiFlutterApiSetupLogger({required LogLevel maxLevel })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_log_level(maxLevel, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSetupLoggerConstMeta,
            argValues: [maxLevel],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiSetupLoggerConstMeta => const TaskConstMeta(
            debugName: "setup_logger",
            argNames: ["maxLevel"],
        );
        

@override Future<void> crateGhApiFlutterApiStartSession({required String sessionId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiStartSessionConstMeta,
            argValues: [sessionId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiStartSessionConstMeta => const TaskConstMeta(
            debugName: "start_session",
            argNames: ["sessionId"],
        );
        

@override Future<void> crateGhApiFlutterApiStopSession({required String sessionId })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiStopSessionConstMeta,
            argValues: [sessionId],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateGhApiFlutterApiStopSessionConstMeta => const TaskConstMeta(
            debugName: "stop_session",
            argNames: ["sessionId"],
        );
        

@override Stream<String> crateGhApiFlutterApiSubscribeClipboardEvents({required String sessionId })  { 
            final sink = RustStreamSink<String>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSubscribeClipboardEventsConstMeta,
            argValues: [sessionId, sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateGhApiFlutterApiSubscribeClipboardEventsConstMeta => const TaskConstMeta(
            debugName: "subscribe_clipboard_events",
            argNames: ["sessionId", "sink"],
        );
        

@override Stream<LogEvent> crateGhApiFlutterApiSubscribeLogs()  { 
            final sink = RustStreamSink<LogEvent>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_StreamSink_log_event_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSubscribeLogsConstMeta,
            argValues: [sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateGhApiFlutterApiSubscribeLogsConstMeta => const TaskConstMeta(
            debugName: "subscribe_logs",
            argNames: ["sink"],
        );
        

@override Stream<SessionEvent> crateGhApiFlutterApiSubscribeSessionEvents({required String sessionId })  { 
            final sink = RustStreamSink<SessionEvent>();
            unawaited(handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(sessionId, serializer);
sse_encode_StreamSink_session_event_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        )
        ,
            constMeta: kCrateGhApiFlutterApiSubscribeSessionEventsConstMeta,
            argValues: [sessionId, sink],
            apiImpl: this,
        )));
            return sink.stream;
             }


        TaskConstMeta get kCrateGhApiFlutterApiSubscribeSessionEventsConstMeta => const TaskConstMeta(
            debugName: "subscribe_session_events",
            argNames: ["sessionId", "sink"],
        );
        



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AnyhowException(raw as String); }

@protected RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
throw UnimplementedError(); }

@protected RustStreamSink<LogEvent> dco_decode_StreamSink_log_event_Sse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
throw UnimplementedError(); }

@protected RustStreamSink<SessionEvent> dco_decode_StreamSink_session_event_Sse(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
throw UnimplementedError(); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected AndroidKeyEventAction dco_decode_android_key_event_action(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AndroidKeyEventAction.values[raw as int]; }

@protected AndroidMotionEventAction dco_decode_android_motion_event_action(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return AndroidMotionEventAction.values[raw as int]; }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected KeyEvent dco_decode_box_autoadd_key_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_key_event(raw); }

@protected ScrollEvent dco_decode_box_autoadd_scroll_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_scroll_event(raw); }

@protected SessionConfig dco_decode_box_autoadd_session_config(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_session_config(raw); }

@protected SessionConfigV2 dco_decode_box_autoadd_session_config_v_2(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_session_config_v_2(raw); }

@protected TouchEvent dco_decode_box_autoadd_touch_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dco_decode_touch_event(raw); }

@protected DecoderMode dco_decode_decoder_mode(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return DecoderMode.values[raw as int]; }

@protected DeviceInfo dco_decode_device_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
                return DeviceInfo(deviceId: dco_decode_String(arr[0]),
model: dco_decode_String(arr[1]),
androidVersion: dco_decode_String(arr[2]),
width: dco_decode_u_32(arr[3]),
height: dco_decode_u_32(arr[4]),
ip: dco_decode_opt_String(arr[5]),); }

@protected ErrorCode dco_decode_error_code(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return ErrorCode.values[raw as int]; }

@protected double dco_decode_f_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as double; }

@protected double dco_decode_f_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as double; }

@protected int dco_decode_i_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected PlatformInt64 dco_decode_i_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeI64(raw); }

@protected KeyEvent dco_decode_key_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return KeyEvent(action: dco_decode_android_key_event_action(arr[0]),
keycode: dco_decode_u_32(arr[1]),
repeat: dco_decode_u_32(arr[2]),
metastate: dco_decode_u_32(arr[3]),); }

@protected List<DeviceInfo> dco_decode_list_device_info(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_device_info).toList(); }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected LogEvent dco_decode_log_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
                return LogEvent(level: dco_decode_String(arr[0]),
target: dco_decode_String(arr[1]),
message: dco_decode_String(arr[2]),
tsMillis: dco_decode_i_64(arr[3]),); }

@protected LogLevel dco_decode_log_level(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return LogLevel.values[raw as int]; }

@protected String? dco_decode_opt_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_String(raw); }

@protected OrientationChangeSource dco_decode_orientation_change_source(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return OrientationChangeSource.values[raw as int]; }

@protected OrientationMode dco_decode_orientation_mode(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return OrientationMode.values[raw as int]; }

@protected RenderPipelineMode dco_decode_render_pipeline_mode(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return RenderPipelineMode.values[raw as int]; }

@protected ScrollEvent dco_decode_scroll_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
                return ScrollEvent(x: dco_decode_f_32(arr[0]),
y: dco_decode_f_32(arr[1]),
width: dco_decode_u_32(arr[2]),
height: dco_decode_u_32(arr[3]),
hscroll: dco_decode_i_32(arr[4]),
vscroll: dco_decode_i_32(arr[5]),); }

@protected SessionConfig dco_decode_session_config(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 13) throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
                return SessionConfig(adbPath: dco_decode_String(arr[0]),
serverPath: dco_decode_String(arr[1]),
deviceId: dco_decode_String(arr[2]),
maxSize: dco_decode_u_32(arr[3]),
bitRate: dco_decode_u_32(arr[4]),
maxFps: dco_decode_u_32(arr[5]),
videoPort: dco_decode_u_16(arr[6]),
controlPort: dco_decode_u_16(arr[7]),
videoEncoder: dco_decode_opt_String(arr[8]),
turnScreenOff: dco_decode_bool(arr[9]),
stayAwake: dco_decode_bool(arr[10]),
scrcpyVerbosity: dco_decode_String(arr[11]),
intraRefreshPeriod: dco_decode_u_32(arr[12]),); }

@protected SessionConfigV2 dco_decode_session_config_v_2(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
                return SessionConfigV2(base: dco_decode_session_config(arr[0]),
renderPipelineMode: dco_decode_render_pipeline_mode(arr[1]),
decoderMode: dco_decode_decoder_mode(arr[2]),); }

@protected SessionEvent dco_decode_session_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
switch (raw[0]) {
                case 0: return SessionEvent_Starting();
case 1: return SessionEvent_Running();
case 2: return SessionEvent_Reconnecting();
case 3: return SessionEvent_Stopped();
case 4: return SessionEvent_Error(code: dco_decode_error_code(raw[1]),message: dco_decode_String(raw[2]),);
case 5: return SessionEvent_OrientationChanged(mode: dco_decode_orientation_mode(raw[1]),source: dco_decode_orientation_change_source(raw[2]),);
case 6: return SessionEvent_ResolutionChanged(width: dco_decode_u_32(raw[1]),height: dco_decode_u_32(raw[2]),newHandle: dco_decode_i_64(raw[3]),generation: dco_decode_u_64(raw[4]),);
                default: throw Exception("unreachable");
            } }

@protected SessionStats dco_decode_session_stats(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
                return SessionStats(fps: dco_decode_f_64(arr[0]),
decodeLatencyMs: dco_decode_u_32(arr[1]),
uploadLatencyMs: dco_decode_u_32(arr[2]),
totalFrames: dco_decode_u_64(arr[3]),
droppedFrames: dco_decode_u_64(arr[4]),); }

@protected SystemKey dco_decode_system_key(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return SystemKey.values[raw as int]; }

@protected TouchEvent dco_decode_touch_event(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 8) throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
                return TouchEvent(action: dco_decode_android_motion_event_action(arr[0]),
pointerId: dco_decode_i_64(arr[1]),
x: dco_decode_f_32(arr[2]),
y: dco_decode_f_32(arr[3]),
pressure: dco_decode_f_32(arr[4]),
width: dco_decode_u_32(arr[5]),
height: dco_decode_u_32(arr[6]),
buttons: dco_decode_u_32(arr[7]),); }

@protected int dco_decode_u_16(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected int dco_decode_u_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected BigInt dco_decode_u_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_String(deserializer);
        return AnyhowException(inner); }

@protected RustStreamSink<String> sse_decode_StreamSink_String_Sse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
throw UnimplementedError('Unreachable ()'); }

@protected RustStreamSink<LogEvent> sse_decode_StreamSink_log_event_Sse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
throw UnimplementedError('Unreachable ()'); }

@protected RustStreamSink<SessionEvent> sse_decode_StreamSink_session_event_Sse(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
throw UnimplementedError('Unreachable ()'); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected AndroidKeyEventAction sse_decode_android_key_event_action(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return AndroidKeyEventAction.values[inner]; }

@protected AndroidMotionEventAction sse_decode_android_motion_event_action(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return AndroidMotionEventAction.values[inner]; }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected KeyEvent sse_decode_box_autoadd_key_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_key_event(deserializer)); }

@protected ScrollEvent sse_decode_box_autoadd_scroll_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_scroll_event(deserializer)); }

@protected SessionConfig sse_decode_box_autoadd_session_config(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_session_config(deserializer)); }

@protected SessionConfigV2 sse_decode_box_autoadd_session_config_v_2(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_session_config_v_2(deserializer)); }

@protected TouchEvent sse_decode_box_autoadd_touch_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_touch_event(deserializer)); }

@protected DecoderMode sse_decode_decoder_mode(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return DecoderMode.values[inner]; }

@protected DeviceInfo sse_decode_device_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_deviceId = sse_decode_String(deserializer);
var var_model = sse_decode_String(deserializer);
var var_androidVersion = sse_decode_String(deserializer);
var var_width = sse_decode_u_32(deserializer);
var var_height = sse_decode_u_32(deserializer);
var var_ip = sse_decode_opt_String(deserializer);
return DeviceInfo(deviceId: var_deviceId, model: var_model, androidVersion: var_androidVersion, width: var_width, height: var_height, ip: var_ip); }

@protected ErrorCode sse_decode_error_code(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return ErrorCode.values[inner]; }

@protected double sse_decode_f_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getFloat32(); }

@protected double sse_decode_f_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getFloat64(); }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getPlatformInt64(); }

@protected KeyEvent sse_decode_key_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_action = sse_decode_android_key_event_action(deserializer);
var var_keycode = sse_decode_u_32(deserializer);
var var_repeat = sse_decode_u_32(deserializer);
var var_metastate = sse_decode_u_32(deserializer);
return KeyEvent(action: var_action, keycode: var_keycode, repeat: var_repeat, metastate: var_metastate); }

@protected List<DeviceInfo> sse_decode_list_device_info(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <DeviceInfo>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_device_info(deserializer)); }
        return ans_;
         }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected LogEvent sse_decode_log_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_level = sse_decode_String(deserializer);
var var_target = sse_decode_String(deserializer);
var var_message = sse_decode_String(deserializer);
var var_tsMillis = sse_decode_i_64(deserializer);
return LogEvent(level: var_level, target: var_target, message: var_message, tsMillis: var_tsMillis); }

@protected LogLevel sse_decode_log_level(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return LogLevel.values[inner]; }

@protected String? sse_decode_opt_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_String(deserializer));
            } else {
                return null;
            }
             }

@protected OrientationChangeSource sse_decode_orientation_change_source(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return OrientationChangeSource.values[inner]; }

@protected OrientationMode sse_decode_orientation_mode(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return OrientationMode.values[inner]; }

@protected RenderPipelineMode sse_decode_render_pipeline_mode(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return RenderPipelineMode.values[inner]; }

@protected ScrollEvent sse_decode_scroll_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_x = sse_decode_f_32(deserializer);
var var_y = sse_decode_f_32(deserializer);
var var_width = sse_decode_u_32(deserializer);
var var_height = sse_decode_u_32(deserializer);
var var_hscroll = sse_decode_i_32(deserializer);
var var_vscroll = sse_decode_i_32(deserializer);
return ScrollEvent(x: var_x, y: var_y, width: var_width, height: var_height, hscroll: var_hscroll, vscroll: var_vscroll); }

@protected SessionConfig sse_decode_session_config(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_adbPath = sse_decode_String(deserializer);
var var_serverPath = sse_decode_String(deserializer);
var var_deviceId = sse_decode_String(deserializer);
var var_maxSize = sse_decode_u_32(deserializer);
var var_bitRate = sse_decode_u_32(deserializer);
var var_maxFps = sse_decode_u_32(deserializer);
var var_videoPort = sse_decode_u_16(deserializer);
var var_controlPort = sse_decode_u_16(deserializer);
var var_videoEncoder = sse_decode_opt_String(deserializer);
var var_turnScreenOff = sse_decode_bool(deserializer);
var var_stayAwake = sse_decode_bool(deserializer);
var var_scrcpyVerbosity = sse_decode_String(deserializer);
var var_intraRefreshPeriod = sse_decode_u_32(deserializer);
return SessionConfig(adbPath: var_adbPath, serverPath: var_serverPath, deviceId: var_deviceId, maxSize: var_maxSize, bitRate: var_bitRate, maxFps: var_maxFps, videoPort: var_videoPort, controlPort: var_controlPort, videoEncoder: var_videoEncoder, turnScreenOff: var_turnScreenOff, stayAwake: var_stayAwake, scrcpyVerbosity: var_scrcpyVerbosity, intraRefreshPeriod: var_intraRefreshPeriod); }

@protected SessionConfigV2 sse_decode_session_config_v_2(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_base = sse_decode_session_config(deserializer);
var var_renderPipelineMode = sse_decode_render_pipeline_mode(deserializer);
var var_decoderMode = sse_decode_decoder_mode(deserializer);
return SessionConfigV2(base: var_base, renderPipelineMode: var_renderPipelineMode, decoderMode: var_decoderMode); }

@protected SessionEvent sse_decode_session_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            var tag_ = sse_decode_i_32(deserializer);
            switch (tag_) { case 0: return SessionEvent_Starting();case 1: return SessionEvent_Running();case 2: return SessionEvent_Reconnecting();case 3: return SessionEvent_Stopped();case 4: var var_code = sse_decode_error_code(deserializer);
var var_message = sse_decode_String(deserializer);
return SessionEvent_Error(code: var_code, message: var_message);case 5: var var_mode = sse_decode_orientation_mode(deserializer);
var var_source = sse_decode_orientation_change_source(deserializer);
return SessionEvent_OrientationChanged(mode: var_mode, source: var_source);case 6: var var_width = sse_decode_u_32(deserializer);
var var_height = sse_decode_u_32(deserializer);
var var_newHandle = sse_decode_i_64(deserializer);
var var_generation = sse_decode_u_64(deserializer);
return SessionEvent_ResolutionChanged(width: var_width, height: var_height, newHandle: var_newHandle, generation: var_generation); default: throw UnimplementedError(''); }
             }

@protected SessionStats sse_decode_session_stats(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_fps = sse_decode_f_64(deserializer);
var var_decodeLatencyMs = sse_decode_u_32(deserializer);
var var_uploadLatencyMs = sse_decode_u_32(deserializer);
var var_totalFrames = sse_decode_u_64(deserializer);
var var_droppedFrames = sse_decode_u_64(deserializer);
return SessionStats(fps: var_fps, decodeLatencyMs: var_decodeLatencyMs, uploadLatencyMs: var_uploadLatencyMs, totalFrames: var_totalFrames, droppedFrames: var_droppedFrames); }

@protected SystemKey sse_decode_system_key(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return SystemKey.values[inner]; }

@protected TouchEvent sse_decode_touch_event(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_action = sse_decode_android_motion_event_action(deserializer);
var var_pointerId = sse_decode_i_64(deserializer);
var var_x = sse_decode_f_32(deserializer);
var var_y = sse_decode_f_32(deserializer);
var var_pressure = sse_decode_f_32(deserializer);
var var_width = sse_decode_u_32(deserializer);
var var_height = sse_decode_u_32(deserializer);
var var_buttons = sse_decode_u_32(deserializer);
return TouchEvent(action: var_action, pointerId: var_pointerId, x: var_x, y: var_y, pressure: var_pressure, width: var_width, height: var_height, buttons: var_buttons); }

@protected int sse_decode_u_16(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint16(); }

@protected int sse_decode_u_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint32(); }

@protected BigInt sse_decode_u_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.message, serializer); }

@protected void sse_encode_StreamSink_String_Sse(RustStreamSink<String> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.setupAndSerialize(codec: SseCodec(
            decodeSuccessData: sse_decode_String,
            decodeErrorData: sse_decode_AnyhowException,
        )), serializer); }

@protected void sse_encode_StreamSink_log_event_Sse(RustStreamSink<LogEvent> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.setupAndSerialize(codec: SseCodec(
            decodeSuccessData: sse_decode_log_event,
            decodeErrorData: sse_decode_AnyhowException,
        )), serializer); }

@protected void sse_encode_StreamSink_session_event_Sse(RustStreamSink<SessionEvent> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.setupAndSerialize(codec: SseCodec(
            decodeSuccessData: sse_decode_session_event,
            decodeErrorData: sse_decode_AnyhowException,
        )), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_android_key_event_action(AndroidKeyEventAction self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_android_motion_event_action(AndroidMotionEventAction self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_box_autoadd_key_event(KeyEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_key_event(self, serializer); }

@protected void sse_encode_box_autoadd_scroll_event(ScrollEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_scroll_event(self, serializer); }

@protected void sse_encode_box_autoadd_session_config(SessionConfig self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_session_config(self, serializer); }

@protected void sse_encode_box_autoadd_session_config_v_2(SessionConfigV2 self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_session_config_v_2(self, serializer); }

@protected void sse_encode_box_autoadd_touch_event(TouchEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_touch_event(self, serializer); }

@protected void sse_encode_decoder_mode(DecoderMode self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_device_info(DeviceInfo self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.deviceId, serializer);
sse_encode_String(self.model, serializer);
sse_encode_String(self.androidVersion, serializer);
sse_encode_u_32(self.width, serializer);
sse_encode_u_32(self.height, serializer);
sse_encode_opt_String(self.ip, serializer);
 }

@protected void sse_encode_error_code(ErrorCode self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_f_32(double self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putFloat32(self); }

@protected void sse_encode_f_64(double self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putFloat64(self); }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putPlatformInt64(self); }

@protected void sse_encode_key_event(KeyEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_android_key_event_action(self.action, serializer);
sse_encode_u_32(self.keycode, serializer);
sse_encode_u_32(self.repeat, serializer);
sse_encode_u_32(self.metastate, serializer);
 }

@protected void sse_encode_list_device_info(List<DeviceInfo> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_device_info(item, serializer); } }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_log_event(LogEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.level, serializer);
sse_encode_String(self.target, serializer);
sse_encode_String(self.message, serializer);
sse_encode_i_64(self.tsMillis, serializer);
 }

@protected void sse_encode_log_level(LogLevel self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_opt_String(String? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_String(self, serializer);
                }
                 }

@protected void sse_encode_orientation_change_source(OrientationChangeSource self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_orientation_mode(OrientationMode self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_render_pipeline_mode(RenderPipelineMode self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_scroll_event(ScrollEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_f_32(self.x, serializer);
sse_encode_f_32(self.y, serializer);
sse_encode_u_32(self.width, serializer);
sse_encode_u_32(self.height, serializer);
sse_encode_i_32(self.hscroll, serializer);
sse_encode_i_32(self.vscroll, serializer);
 }

@protected void sse_encode_session_config(SessionConfig self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_String(self.adbPath, serializer);
sse_encode_String(self.serverPath, serializer);
sse_encode_String(self.deviceId, serializer);
sse_encode_u_32(self.maxSize, serializer);
sse_encode_u_32(self.bitRate, serializer);
sse_encode_u_32(self.maxFps, serializer);
sse_encode_u_16(self.videoPort, serializer);
sse_encode_u_16(self.controlPort, serializer);
sse_encode_opt_String(self.videoEncoder, serializer);
sse_encode_bool(self.turnScreenOff, serializer);
sse_encode_bool(self.stayAwake, serializer);
sse_encode_String(self.scrcpyVerbosity, serializer);
sse_encode_u_32(self.intraRefreshPeriod, serializer);
 }

@protected void sse_encode_session_config_v_2(SessionConfigV2 self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_session_config(self.base, serializer);
sse_encode_render_pipeline_mode(self.renderPipelineMode, serializer);
sse_encode_decoder_mode(self.decoderMode, serializer);
 }

@protected void sse_encode_session_event(SessionEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
switch (self) { case SessionEvent_Starting(): sse_encode_i_32(0, serializer); case SessionEvent_Running(): sse_encode_i_32(1, serializer); case SessionEvent_Reconnecting(): sse_encode_i_32(2, serializer); case SessionEvent_Stopped(): sse_encode_i_32(3, serializer); case SessionEvent_Error(code: final code,message: final message): sse_encode_i_32(4, serializer); sse_encode_error_code(code, serializer);
sse_encode_String(message, serializer);
case SessionEvent_OrientationChanged(mode: final mode,source: final source): sse_encode_i_32(5, serializer); sse_encode_orientation_mode(mode, serializer);
sse_encode_orientation_change_source(source, serializer);
case SessionEvent_ResolutionChanged(width: final width,height: final height,newHandle: final newHandle,generation: final generation): sse_encode_i_32(6, serializer); sse_encode_u_32(width, serializer);
sse_encode_u_32(height, serializer);
sse_encode_i_64(newHandle, serializer);
sse_encode_u_64(generation, serializer);
  } }

@protected void sse_encode_session_stats(SessionStats self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_f_64(self.fps, serializer);
sse_encode_u_32(self.decodeLatencyMs, serializer);
sse_encode_u_32(self.uploadLatencyMs, serializer);
sse_encode_u_64(self.totalFrames, serializer);
sse_encode_u_64(self.droppedFrames, serializer);
 }

@protected void sse_encode_system_key(SystemKey self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_touch_event(TouchEvent self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_android_motion_event_action(self.action, serializer);
sse_encode_i_64(self.pointerId, serializer);
sse_encode_f_32(self.x, serializer);
sse_encode_f_32(self.y, serializer);
sse_encode_f_32(self.pressure, serializer);
sse_encode_u_32(self.width, serializer);
sse_encode_u_32(self.height, serializer);
sse_encode_u_32(self.buttons, serializer);
 }

@protected void sse_encode_u_16(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint16(self); }

@protected void sse_encode_u_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint32(self); }

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }
                }
                
