// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'model.freezed.dart';

            

            

            /// Android 按键事件动作（Flutter API 输入模型）。
enum AndroidKeyEventAction {
                    down,
up,
                    ;
                    
                }

/// Android 触摸事件动作（Flutter API 输入模型）。
enum AndroidMotionEventAction {
                    down,
up,
move,
cancel,
pointerDown,
pointerUp,
hoverMove,
hoverEnter,
hoverExit,
                    ;
                    
                }

/// 解码器选择模式（新增配置，仅用于 V2 API）。
enum DecoderMode {
                    preferHardware,
forceHardware,
forceSoftware,
                    ;
                    
                }

/// 设备信息（面向 Flutter 的稳定返回模型）。
class DeviceInfo  {
                /// ADB 设备序列号。
final String deviceId;
/// 设备型号，例如 `SM-G9810`。
final String model;
/// Android 版本，例如 `13`。
final String androidVersion;
/// 屏幕宽度（像素）。
final int width;
/// 屏幕高度（像素）。
final int height;
/// 可选 IP（Wi-Fi 设备时可填）。
final String? ip;

                const DeviceInfo({required this.deviceId ,required this.model ,required this.androidVersion ,required this.width ,required this.height ,this.ip ,});

                
                

                
        @override
        int get hashCode => deviceId.hashCode^model.hashCode^androidVersion.hashCode^width.hashCode^height.hashCode^ip.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is DeviceInfo &&
                runtimeType == other.runtimeType
                && deviceId == other.deviceId&& model == other.model&& androidVersion == other.androidVersion&& width == other.width&& height == other.height&& ip == other.ip;
        
            }

/// 会话事件/调用错误码（供上层统一处理）。
enum ErrorCode {
                    invalidSession,
alreadyRunning,
notRunning,
deviceDisconnected,
decodeFailed,
textureFailed,
controlFailed,
internal,
                    ;
                    
                }

/// 按键事件（Flutter API 输入模型）。
class KeyEvent  {
                final AndroidKeyEventAction action;
final int keycode;
final int repeat;
final int metastate;

                const KeyEvent({required this.action ,required this.keycode ,required this.repeat ,required this.metastate ,});

                
                

                
        @override
        int get hashCode => action.hashCode^keycode.hashCode^repeat.hashCode^metastate.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is KeyEvent &&
                runtimeType == other.runtimeType
                && action == other.action&& keycode == other.keycode&& repeat == other.repeat&& metastate == other.metastate;
        
            }

/// Rust -> Dart 日志事件模型（FRB 流传输）。
class LogEvent  {
                /// 日志级别文本（trace/debug/info/warn/error）。
final String level;
/// 日志来源 target。
final String target;
/// 日志正文。
final String message;
/// UTC 毫秒时间戳。
final PlatformInt64 tsMillis;

                const LogEvent({required this.level ,required this.target ,required this.message ,required this.tsMillis ,});

                
                

                
        @override
        int get hashCode => level.hashCode^target.hashCode^message.hashCode^tsMillis.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is LogEvent &&
                runtimeType == other.runtimeType
                && level == other.level&& target == other.target&& message == other.message&& tsMillis == other.tsMillis;
        
            }

/// DLL 侧日志级别。
enum LogLevel {
                    trace,
debug,
info,
warn,
error,
                    ;
                    
                }

/// 方向变更来源。
enum OrientationChangeSource {
                    /// 上层 API 主动发起。
manualApi,
/// 系统自动旋转（传感器/系统策略）。
autoSensor,
                    ;
                    
                }

/// 会话方向模式。
enum OrientationMode {
                    auto,
portrait,
landscape,
                    ;
                    
                }

/// 渲染链路模式（新增配置，仅用于 V2 API）。
enum RenderPipelineMode {
                    /// 维持现有共享句柄链路。
original,
/// V2：纯 CPU BGRA + PixelBuffer 链路（不使用共享纹理渲染）。
cpuPixelBufferV2,
                    ;
                    
                }

/// 滚轮事件（Flutter API 输入模型）。
class ScrollEvent  {
                final double x;
final double y;
final int width;
final int height;
final int hscroll;
final int vscroll;

                const ScrollEvent({required this.x ,required this.y ,required this.width ,required this.height ,required this.hscroll ,required this.vscroll ,});

                
                

                
        @override
        int get hashCode => x.hashCode^y.hashCode^width.hashCode^height.hashCode^hscroll.hashCode^vscroll.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is ScrollEvent &&
                runtimeType == other.runtimeType
                && x == other.x&& y == other.y&& width == other.width&& height == other.height&& hscroll == other.hscroll&& vscroll == other.vscroll;
        
            }

/// 创建会话所需配置（与 Flutter 桥接模型对齐）。
class SessionConfig  {
                /// adb 可执行文件路径。
final String adbPath;
/// scrcpy-server 路径。
final String serverPath;
/// 目标设备 ID。
final String deviceId;
/// 最大分辨率（长边），0 表示不限制。
final int maxSize;
/// 视频码率（bps）。
final int bitRate;
/// 最大帧率，0 表示不限制。
final int maxFps;
/// 视频端口。
final int videoPort;
/// 控制端口。
final int controlPort;
/// 指定编码器名称（可选）。
final String? videoEncoder;
/// 是否在会话启动后关闭设备屏幕。
final bool turnScreenOff;
/// 是否保持设备防休眠。
final bool stayAwake;
/// scrcpy 日志级别字符串（例如 `info`）。
final String scrcpyVerbosity;
/// 强制生成 IDR 关键帧的周期（秒），0 表示由编码器自己决定。
final int intraRefreshPeriod;

                const SessionConfig({required this.adbPath ,required this.serverPath ,required this.deviceId ,required this.maxSize ,required this.bitRate ,required this.maxFps ,required this.videoPort ,required this.controlPort ,this.videoEncoder ,required this.turnScreenOff ,required this.stayAwake ,required this.scrcpyVerbosity ,required this.intraRefreshPeriod ,});

                
                

                
        @override
        int get hashCode => adbPath.hashCode^serverPath.hashCode^deviceId.hashCode^maxSize.hashCode^bitRate.hashCode^maxFps.hashCode^videoPort.hashCode^controlPort.hashCode^videoEncoder.hashCode^turnScreenOff.hashCode^stayAwake.hashCode^scrcpyVerbosity.hashCode^intraRefreshPeriod.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SessionConfig &&
                runtimeType == other.runtimeType
                && adbPath == other.adbPath&& serverPath == other.serverPath&& deviceId == other.deviceId&& maxSize == other.maxSize&& bitRate == other.bitRate&& maxFps == other.maxFps&& videoPort == other.videoPort&& controlPort == other.controlPort&& videoEncoder == other.videoEncoder&& turnScreenOff == other.turnScreenOff&& stayAwake == other.stayAwake&& scrcpyVerbosity == other.scrcpyVerbosity&& intraRefreshPeriod == other.intraRefreshPeriod;
        
            }

/// 创建会话所需扩展配置（V2）。
///
/// 说明：
/// - `base` 与旧版 `SessionConfig` 完全一致；
/// - `render_pipeline_mode`/`decoder_mode` 仅影响新 API；
/// - 旧 API 不读取这些字段，保证兼容。
class SessionConfigV2  {
                final SessionConfig base;
final RenderPipelineMode renderPipelineMode;
final DecoderMode decoderMode;

                const SessionConfigV2({required this.base ,required this.renderPipelineMode ,required this.decoderMode ,});

                
                

                
        @override
        int get hashCode => base.hashCode^renderPipelineMode.hashCode^decoderMode.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SessionConfigV2 &&
                runtimeType == other.runtimeType
                && base == other.base&& renderPipelineMode == other.renderPipelineMode&& decoderMode == other.decoderMode;
        
            }

@freezed
                sealed class SessionEvent with _$SessionEvent  {
                    const SessionEvent._();

                     const factory SessionEvent.starting() = SessionEvent_Starting;
 const factory SessionEvent.running() = SessionEvent_Running;
 const factory SessionEvent.reconnecting() = SessionEvent_Reconnecting;
 const factory SessionEvent.stopped() = SessionEvent_Stopped;
 const factory SessionEvent.error({   required ErrorCode code ,  required String message , }) = SessionEvent_Error;
 const factory SessionEvent.orientationChanged({   required OrientationMode mode ,  required OrientationChangeSource source , }) = SessionEvent_OrientationChanged;
 const factory SessionEvent.resolutionChanged({   required int width ,  required int height ,  required PlatformInt64 newHandle ,  required BigInt generation , }) = SessionEvent_ResolutionChanged;

                    

                    
                }

/// 会话统计信息（供上层监控与调试）。
class SessionStats  {
                final double fps;
final int decodeLatencyMs;
final int uploadLatencyMs;
final BigInt totalFrames;
final BigInt droppedFrames;

                const SessionStats({required this.fps ,required this.decodeLatencyMs ,required this.uploadLatencyMs ,required this.totalFrames ,required this.droppedFrames ,});

                
                

                
        @override
        int get hashCode => fps.hashCode^decodeLatencyMs.hashCode^uploadLatencyMs.hashCode^totalFrames.hashCode^droppedFrames.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SessionStats &&
                runtimeType == other.runtimeType
                && fps == other.fps&& decodeLatencyMs == other.decodeLatencyMs&& uploadLatencyMs == other.uploadLatencyMs&& totalFrames == other.totalFrames&& droppedFrames == other.droppedFrames;
        
            }

/// 系统按键类型（语义键）。
enum SystemKey {
                    home,
back,
recent,
powerMenu,
volumeUp,
volumeDown,
rotateScreen,
                    ;
                    
                }

/// 触摸事件（Flutter API 输入模型）。
class TouchEvent  {
                final AndroidMotionEventAction action;
final PlatformInt64 pointerId;
final double x;
final double y;
final double pressure;
final int width;
final int height;
final int buttons;

                const TouchEvent({required this.action ,required this.pointerId ,required this.x ,required this.y ,required this.pressure ,required this.width ,required this.height ,required this.buttons ,});

                
                

                
        @override
        int get hashCode => action.hashCode^pointerId.hashCode^x.hashCode^y.hashCode^pressure.hashCode^width.hashCode^height.hashCode^buttons.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is TouchEvent &&
                runtimeType == other.runtimeType
                && action == other.action&& pointerId == other.pointerId&& x == other.x&& y == other.y&& pressure == other.pressure&& width == other.width&& height == other.height&& buttons == other.buttons;
        
            }

/// YOLO 推理配置。
class YoloConfig  {
                /// ONNX 模型绝对路径。
final String modelPath;
/// 网络输入宽度（例如 640）。
final int inputWidth;
/// 网络输入高度（例如 640）。
final int inputHeight;
/// 置信度阈值。
final double confidenceThreshold;
/// NMS IoU 阈值。
final double iouThreshold;
/// 每帧最大检测框数量。
final int maxDetections;
/// 推理后端（仅硬件后端）。
final YoloExecutionProvider provider;
/// 可选设备索引（CUDA/TensorRT 场景可用）。
final int? deviceIndex;
/// 推理限频（每秒最多处理多少帧）。
final int maxInferFps;

                const YoloConfig({required this.modelPath ,required this.inputWidth ,required this.inputHeight ,required this.confidenceThreshold ,required this.iouThreshold ,required this.maxDetections ,required this.provider ,this.deviceIndex ,required this.maxInferFps ,});

                
                

                
        @override
        int get hashCode => modelPath.hashCode^inputWidth.hashCode^inputHeight.hashCode^confidenceThreshold.hashCode^iouThreshold.hashCode^maxDetections.hashCode^provider.hashCode^deviceIndex.hashCode^maxInferFps.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is YoloConfig &&
                runtimeType == other.runtimeType
                && modelPath == other.modelPath&& inputWidth == other.inputWidth&& inputHeight == other.inputHeight&& confidenceThreshold == other.confidenceThreshold&& iouThreshold == other.iouThreshold&& maxDetections == other.maxDetections&& provider == other.provider&& deviceIndex == other.deviceIndex&& maxInferFps == other.maxInferFps;
        
            }

/// 单个检测框结果。
class YoloDetection  {
                /// 类别 ID。
final int classId;
/// 类别名称（可选）。
final String? label;
/// 置信度分数。
final double score;
/// 左上角 x（像素坐标）。
final double x;
/// 左上角 y（像素坐标）。
final double y;
/// 宽度（像素）。
final double width;
/// 高度（像素）。
final double height;

                const YoloDetection({required this.classId ,this.label ,required this.score ,required this.x ,required this.y ,required this.width ,required this.height ,});

                
                

                
        @override
        int get hashCode => classId.hashCode^label.hashCode^score.hashCode^x.hashCode^y.hashCode^width.hashCode^height.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is YoloDetection &&
                runtimeType == other.runtimeType
                && classId == other.classId&& label == other.label&& score == other.score&& x == other.x&& y == other.y&& width == other.width&& height == other.height;
        
            }

/// YOLO 推理执行后端（仅硬件后端，不允许 CPU 推理）。
enum YoloExecutionProvider {
                    /// Windows DirectML（兼容 NVIDIA/AMD/Intel）。
directMl,
/// NVIDIA CUDA（依赖 CUDA 环境）。
cuda,
/// NVIDIA TensorRT（高性能，部署要求更高）。
tensorRt,
                    ;
                    
                }

/// 单帧 YOLO 推理结果事件。
class YoloFrameResult  {
                /// 关联会话 ID。
final String sessionId;
/// 视频帧 ID。
final BigInt frameId;
/// 原始帧宽度。
final int frameWidth;
/// 原始帧高度。
final int frameHeight;
/// 推理耗时（毫秒）。
final int inferLatencyMs;
/// 检测框列表。
final List<YoloDetection> detections;

                const YoloFrameResult({required this.sessionId ,required this.frameId ,required this.frameWidth ,required this.frameHeight ,required this.inferLatencyMs ,required this.detections ,});

                
                

                
        @override
        int get hashCode => sessionId.hashCode^frameId.hashCode^frameWidth.hashCode^frameHeight.hashCode^inferLatencyMs.hashCode^detections.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is YoloFrameResult &&
                runtimeType == other.runtimeType
                && sessionId == other.sessionId&& frameId == other.frameId&& frameWidth == other.frameWidth&& frameHeight == other.frameHeight&& inferLatencyMs == other.inferLatencyMs&& detections == other.detections;
        
            }
            