// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PixelFrame`, `SessionEventCallbackHolder`, `V1CallbackHolder`, `V2CallbackHolder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`


            /// 存储一帧 BGRA，返回可跨 FFI 使用的帧 ID。
///
/// 说明：
/// - 当前主链路已改为“直接回调推帧”，该帧池接口只作为兼容保留；
/// - 后续确认无引用后可在单独变更中删除。
Future<BigInt>  storeFrame({required int width , required int height , required List<int> bgra }) => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiStoreFrame(width: width, height: height, bgra: bgra);

Future<BigInt>  nextFrameId() => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiNextFrameId();

/// 注册 V2 帧回调（由 Windows Runner 调用一次）。
///
/// 回调触发线程：Rust 解码工作线程。
Future<bool>  rsRegisterV2FrameCallback({ExternCFnUserDataMutCVoidFrameIdU64DataConstU8DataLenUsizeWidthU32HeightU32StrideU32PixelFormatU32GenerationU64PtsI64? callback , required MutCVoid userData }) => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiRsRegisterV2FrameCallback(callback: callback, userData: userData);

/// 注册 V1 帧回调（DXGI 元信息回调）。
///
/// 回调触发线程：Rust 解码工作线程。
Future<bool>  rsRegisterV1FrameCallback({ExternCFnUserDataMutCVoidHandleI64WidthU32HeightU32GenerationU64PtsI64? callback , required MutCVoid userData }) => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiRsRegisterV1FrameCallback(callback: callback, userData: userData);

/// 注册 SessionEvent 回调（由 Windows Runner 调用一次）。
///
/// 回调触发线程：Rust 运行时 worker 线程。
Future<bool>  rsRegisterSessionEventCallback({ExternCFnUserDataMutCVoidSessionIdConstU8SessionIdLenUsizeEventJsonConstU8EventJsonLenUsize? callback , required MutCVoid userData }) => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiRsRegisterSessionEventCallback(callback: callback, userData: userData);

/// 向外部（Runner）推送一条 V2 新帧通知。
Future<void>  notifyV2Frame({required BigInt frameId , required int width , required int height , required BigInt generation , required PlatformInt64 pts }) => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiNotifyV2Frame(frameId: frameId, width: width, height: height, generation: generation, pts: pts);

/// 向外部（Runner）推送一条 V2 新帧通知（直接携带像素内存与元数据）。
Future<void>  notifyV2FrameRaw({required BigInt frameId , required List<int> data , required int width , required int height , required int stride , required int pixelFormat , required BigInt generation , required PlatformInt64 pts }) => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiNotifyV2FrameRaw(frameId: frameId, data: data, width: width, height: height, stride: stride, pixelFormat: pixelFormat, generation: generation, pts: pts);

/// 向外部（Runner）推送一条 V1 句柄帧通知。
Future<void>  notifyV1Frame({required PlatformInt64 handle , required int width , required int height , required BigInt generation , required PlatformInt64 pts }) => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiNotifyV1Frame(handle: handle, width: width, height: height, generation: generation, pts: pts);

/// 向外部（Runner）推送一条会话事件通知。
///
/// `event_json` 要求为 UTF-8 JSON 字节（通常由 `serde_json::to_vec` 生成）。
Future<void>  notifySessionEvent({required String sessionId , required List<int> eventJson }) => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiNotifySessionEvent(sessionId: sessionId, eventJson: eventJson);

/// 从 Rust 内存池复制指定帧到外部缓冲。
///
/// 返回值：实际复制字节数，0 表示失败。
Future<BigInt>  rsCopyBgraFrame({required BigInt frameId , required MutU8 dst , required BigInt dstLen , required MutU32 outWidth , required MutU32 outHeight }) => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiRsCopyBgraFrame(frameId: frameId, dst: dst, dstLen: dstLen, outWidth: outWidth, outHeight: outHeight);

Future<void>  rsReleaseBgraFrame({required BigInt frameId }) => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiRsReleaseBgraFrame(frameId: frameId);

Future<BigInt>  rsDebugFrameStoreLen() => RustLib.instance.api.crateRustScrcpyApiFlutterCallbackApiRsDebugFrameStoreLen();

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* mut c_void>>
                abstract class MutCVoid implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* mut u32>>
                abstract class MutU32 implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* mut u8>>
                abstract class MutU8 implements RustOpaqueInterface {
                    

                    
                }
                
            