// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'model.freezed.dart';

            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`


            

            /// 解码器选择模式（新增配置，仅用于 V2 API）。
enum DecoderMode {
                    preferHardware,
forceHardware,
forceSoftware,
                    ;
                    
                }

/// 设备信息（面向 Flutter 的稳定返回模型）。
class DeviceInfo  {
                /// ADB 设备序列号。
final String deviceId;
/// 设备型号，例如 `SM-G9810`。
final String model;
/// Android 版本，例如 `13`。
final String androidVersion;
/// 屏幕宽度（像素）。
final int width;
/// 屏幕高度（像素）。
final int height;
/// 可选 IP（Wi-Fi 设备时可填）。
final String? ip;

                const DeviceInfo({required this.deviceId ,required this.model ,required this.androidVersion ,required this.width ,required this.height ,this.ip ,});

                
                

                
        @override
        int get hashCode => deviceId.hashCode^model.hashCode^androidVersion.hashCode^width.hashCode^height.hashCode^ip.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is DeviceInfo &&
                runtimeType == other.runtimeType
                && deviceId == other.deviceId&& model == other.model&& androidVersion == other.androidVersion&& width == other.width&& height == other.height&& ip == other.ip;
        
            }

/// 会话事件/调用错误码（供上层统一处理）。
enum ErrorCode {
                    invalidSession,
alreadyRunning,
notRunning,
deviceDisconnected,
decodeFailed,
textureFailed,
controlFailed,
internal,
                    ;
                    
                }

/// DLL 侧日志级别。
enum LogLevel {
                    trace,
debug,
info,
warn,
error,
                    ;
                    
                }

/// 方向变更来源。
enum OrientationChangeSource {
                    /// 上层 API 主动发起。
manualApi,
/// 系统自动旋转（传感器/系统策略）。
autoSensor,
                    ;
                    
                }

/// 会话方向模式。
enum OrientationMode {
                    auto,
portrait,
landscape,
                    ;
                    
                }

/// 渲染链路模式（新增配置，仅用于 V2 API）。
enum RenderPipelineMode {
                    /// 维持现有共享句柄链路。
original,
/// V2：纯 CPU BGRA + PixelBuffer 链路（不使用共享纹理渲染）。
cpuPixelBufferV2,
                    ;
                    
                }

/// 创建会话所需配置（与 Flutter 桥接模型对齐）。
class SessionConfig  {
                /// adb 可执行文件路径。
final String adbPath;
/// scrcpy-server 路径。
final String serverPath;
/// 目标设备 ID。
final String deviceId;
/// 最大分辨率（长边），0 表示不限制。
final int maxSize;
/// 视频码率（bps）。
final int bitRate;
/// 最大帧率，0 表示不限制。
final int maxFps;
/// 视频端口。
final int videoPort;
/// 控制端口。
final int controlPort;
/// 指定编码器名称（可选）。
final String? videoEncoder;
/// 是否在会话启动后关闭设备屏幕。
final bool turnScreenOff;
/// 是否保持设备常亮。
final bool stayAwake;
/// scrcpy 日志级别字符串（例如 `info`）。
final String scrcpyVerbosity;
/// 强制生成 IDR 关键帧的周期（秒），0 表示由编码器自己决定。
final int intraRefreshPeriod;

                const SessionConfig({required this.adbPath ,required this.serverPath ,required this.deviceId ,required this.maxSize ,required this.bitRate ,required this.maxFps ,required this.videoPort ,required this.controlPort ,this.videoEncoder ,required this.turnScreenOff ,required this.stayAwake ,required this.scrcpyVerbosity ,required this.intraRefreshPeriod ,});

                
                

                
        @override
        int get hashCode => adbPath.hashCode^serverPath.hashCode^deviceId.hashCode^maxSize.hashCode^bitRate.hashCode^maxFps.hashCode^videoPort.hashCode^controlPort.hashCode^videoEncoder.hashCode^turnScreenOff.hashCode^stayAwake.hashCode^scrcpyVerbosity.hashCode^intraRefreshPeriod.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SessionConfig &&
                runtimeType == other.runtimeType
                && adbPath == other.adbPath&& serverPath == other.serverPath&& deviceId == other.deviceId&& maxSize == other.maxSize&& bitRate == other.bitRate&& maxFps == other.maxFps&& videoPort == other.videoPort&& controlPort == other.controlPort&& videoEncoder == other.videoEncoder&& turnScreenOff == other.turnScreenOff&& stayAwake == other.stayAwake&& scrcpyVerbosity == other.scrcpyVerbosity&& intraRefreshPeriod == other.intraRefreshPeriod;
        
            }

/// 创建会话所需扩展配置（V2）。
///
/// 说明：
/// - `base` 与旧版 `SessionConfig` 完全一致；
/// - `render_pipeline_mode`/`decoder_mode` 仅影响新 API；
/// - 旧 API 不读取这些字段，保证兼容。
class SessionConfigV2  {
                final SessionConfig base;
final RenderPipelineMode renderPipelineMode;
final DecoderMode decoderMode;

                const SessionConfigV2({required this.base ,required this.renderPipelineMode ,required this.decoderMode ,});

                
                

                
        @override
        int get hashCode => base.hashCode^renderPipelineMode.hashCode^decoderMode.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SessionConfigV2 &&
                runtimeType == other.runtimeType
                && base == other.base&& renderPipelineMode == other.renderPipelineMode&& decoderMode == other.decoderMode;
        
            }

@freezed
                sealed class SessionEvent with _$SessionEvent  {
                    const SessionEvent._();

                     const factory SessionEvent.starting() = SessionEvent_Starting;
 const factory SessionEvent.running() = SessionEvent_Running;
 const factory SessionEvent.reconnecting() = SessionEvent_Reconnecting;
 const factory SessionEvent.stopped() = SessionEvent_Stopped;
 const factory SessionEvent.error({   required ErrorCode code ,  required String message , }) = SessionEvent_Error;
 const factory SessionEvent.orientationChanged({   required OrientationMode mode ,  required OrientationChangeSource source , }) = SessionEvent_OrientationChanged;
 const factory SessionEvent.resolutionChanged({   required int width ,  required int height ,  required PlatformInt64 newHandle ,  required BigInt generation , }) = SessionEvent_ResolutionChanged;

                    

                    
                }

/// 会话统计信息（供上层监控与调试）。
class SessionStats  {
                final double fps;
final int decodeLatencyMs;
final int uploadLatencyMs;
final BigInt totalFrames;
final BigInt droppedFrames;

                const SessionStats({required this.fps ,required this.decodeLatencyMs ,required this.uploadLatencyMs ,required this.totalFrames ,required this.droppedFrames ,});

                
                

                
        @override
        int get hashCode => fps.hashCode^decodeLatencyMs.hashCode^uploadLatencyMs.hashCode^totalFrames.hashCode^droppedFrames.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SessionStats &&
                runtimeType == other.runtimeType
                && fps == other.fps&& decodeLatencyMs == other.decodeLatencyMs&& uploadLatencyMs == other.uploadLatencyMs&& totalFrames == other.totalFrames&& droppedFrames == other.droppedFrames;
        
            }

/// 系统按键类型（语义键）。
enum SystemKey {
                    home,
back,
recent,
powerMenu,
volumeUp,
volumeDown,
rotateScreen,
                    ;
                    
                }

/// 纹理帧元信息。
class TextureFrame  {
                final PlatformInt64 handle;
final int width;
final int height;
final BigInt generation;
final PlatformInt64 pts;

                const TextureFrame({required this.handle ,required this.width ,required this.height ,required this.generation ,required this.pts ,});

                
                

                
        @override
        int get hashCode => handle.hashCode^width.hashCode^height.hashCode^generation.hashCode^pts.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is TextureFrame &&
                runtimeType == other.runtimeType
                && handle == other.handle&& width == other.width&& height == other.height&& generation == other.generation&& pts == other.pts;
        
            }
            