// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../scrcpy/control.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `bgra_to_rgba`, `map_decoder_mode`, `map_orientation`, `new_with_options`, `new`, `now_millis`, `push_event`, `push_frame`, `send_runtime_cmd`, `send_system_key_async`, `update_stats`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HwRecoveryState`, `RuntimeCommand`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`


            

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlowMonitor>>
                abstract class FlowMonitor implements RustOpaqueInterface {
                    static Future<FlowMonitor>  default_()=>RustLib.instance.api.crateRustScrcpyApiRuntimeFlowMonitorDefault();



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealSessionRuntime>>
                abstract class RealSessionRuntime implements RustOpaqueInterface, SessionRuntime {
                    /// 返回运行态标记。
 Future<bool>  isRunning();


/// 轮询并清空当前事件队列。
 Future<List<SessionEvent>>  pollSessionEvents();


/// 轮询最新可渲染帧。
///
/// 策略：每次只返回“最后一帧”，并统计被覆盖/丢弃的历史帧。
 Future<List<TextureFrame>>  pollTextureFrames();


/// 下发 IDR 请求命令到 worker。
 Future<void>  requestIdr();


/// 下发按键事件命令到 worker。
 Future<void>  sendKey({required KeyEvent event });


/// 下发滚动事件命令到 worker。
 Future<void>  sendScroll({required ScrollEvent event });


/// 下发系统按键命令到 worker。
 Future<void>  sendSystemKey({required SystemKey key });


/// 下发文本输入命令到 worker。
 Future<void>  sendText({required String text });


/// 下发触摸事件命令到 worker。
 Future<void>  sendTouch({required TouchEvent event });


/// 下发剪贴板命令到 worker。
 Future<void>  setClipboard({required String text , required bool paste });


/// 下发方向切换命令到 worker。
 Future<void>  setOrientationMode({required OrientationMode mode });


/// 启动会话 worker。
///
/// 流程：
/// 1) 建立 ADB/scrcpy 视频与控制链路；
/// 2) 启动解码管线；
/// 3) 在循环中消费命令、视频包与解码输出；
/// 4) 产出帧队列与事件队列供 FFI 轮询。
 Future<void>  start();


/// 获取当前统计快照（锁失败时返回零值兜底）。
 Future<SessionStats>  stats();


/// 停止 worker，并清空运行时缓存队列。
 Future<void>  stop();



                    
                }
                


                abstract class SessionRuntime {
                    /// 是否处于运行态。
 Future<bool>  isRunning();


/// 拉取会话事件（轮询语义）。
 Future<List<SessionEvent>>  pollSessionEvents();


/// 拉取可渲染帧（轮询语义）。
 Future<List<TextureFrame>>  pollTextureFrames();


/// 请求关键帧（IDR）。
 Future<void>  requestIdr();


/// 发送按键事件。
 Future<void>  sendKey({required KeyEvent event });


/// 发送滚动事件。
 Future<void>  sendScroll({required ScrollEvent event });


/// 发送系统按键语义事件。
 Future<void>  sendSystemKey({required SystemKey key });


/// 发送文本输入。
 Future<void>  sendText({required String text });


/// 发送触摸事件。
 Future<void>  sendTouch({required TouchEvent event });


/// 设置剪贴板。
 Future<void>  setClipboard({required String text , required bool paste });


/// 设置方向意图。
 Future<void>  setOrientationMode({required OrientationMode mode });


/// 启动运行时：拉起 worker、建立 scrcpy 链路并开始解码轮询。
 Future<void>  start();


/// 返回统计快照。
 Future<SessionStats>  stats();


/// 停止运行时：停止 worker 并释放会话级临时资源。
 Future<void>  stop();


                }
                
            