// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../scrcpy/control.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `invalid_session_error`, `lock_sessions`, `map_level`, `new_session_id`, `parse_size_pair`, `parse_wm_size`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ApiSession`


            /// 初始化 DLL 日志系统。
///
/// 行为：
/// - 仅首次调用生效，后续调用直接返回 `Ok(())`；
/// - 日志会包含线程、文件与行号，便于跨线程问题定位。
Future<void>  setupLogger({required LogLevel maxLevel }) => RustLib.instance.api.crateRustScrcpyApiServiceSetupLogger(maxLevel: maxLevel);

/// 列出当前 ADB 在线设备。
///
/// 返回：
/// - 仅保证 `device_id` 可用；
/// - 型号/系统版本/分辨率为占位值，需配合 `get_device_info()` 获取详情。
Future<List<DeviceInfo>>  listDevices({required String adbPath }) => RustLib.instance.api.crateRustScrcpyApiServiceListDevices(adbPath: adbPath);

/// 读取单个设备详情。
///
/// 数据来源：
/// - 通过 ADB shell 读取品牌、型号、Android 版本与 `wm size`；
/// - 若部分字段不可用，按降级策略填充默认值。
Future<DeviceInfo>  getDeviceInfo({required String adbPath , required String deviceId }) => RustLib.instance.api.crateRustScrcpyApiServiceGetDeviceInfo(adbPath: adbPath, deviceId: deviceId);

/// 创建会话（仅创建，不启动）。
Future<String>  createSession({required SessionConfig config }) => RustLib.instance.api.crateRustScrcpyApiServiceCreateSession(config: config);

/// 创建会话（V2：支持解码模式与渲染模式配置，旧 API 不受影响）。
Future<String>  createSessionV2({required SessionConfigV2 config }) => RustLib.instance.api.crateRustScrcpyApiServiceCreateSessionV2(config: config);

/// 启动会话。
Future<void>  startSession({required String sessionId }) => RustLib.instance.api.crateRustScrcpyApiServiceStartSession(sessionId: sessionId);

/// 停止会话。
Future<void>  stopSession({required String sessionId }) => RustLib.instance.api.crateRustScrcpyApiServiceStopSession(sessionId: sessionId);

/// 销毁会话并移除状态。
Future<void>  disposeSession({required String sessionId }) => RustLib.instance.api.crateRustScrcpyApiServiceDisposeSession(sessionId: sessionId);

/// 向目标会话发送触摸事件。
Future<void>  sendTouch({required String sessionId , required TouchEvent event }) => RustLib.instance.api.crateRustScrcpyApiServiceSendTouch(sessionId: sessionId, event: event);

/// 向目标会话发送按键事件。
Future<void>  sendKey({required String sessionId , required KeyEvent event }) => RustLib.instance.api.crateRustScrcpyApiServiceSendKey(sessionId: sessionId, event: event);

/// 向目标会话发送滚轮事件。
Future<void>  sendScroll({required String sessionId , required ScrollEvent event }) => RustLib.instance.api.crateRustScrcpyApiServiceSendScroll(sessionId: sessionId, event: event);

/// 向目标会话发送文本输入。
Future<void>  sendText({required String sessionId , required String text }) => RustLib.instance.api.crateRustScrcpyApiServiceSendText(sessionId: sessionId, text: text);

/// 向目标会话发送系统按键语义事件（Home/Back/音量等）。
Future<void>  sendSystemKey({required String sessionId , required SystemKey key }) => RustLib.instance.api.crateRustScrcpyApiServiceSendSystemKey(sessionId: sessionId, key: key);

/// 设置设备剪贴板内容。
Future<void>  setClipboard({required String sessionId , required String text , required bool paste }) => RustLib.instance.api.crateRustScrcpyApiServiceSetClipboard(sessionId: sessionId, text: text, paste: paste);

/// 设置会话方向模式（主动旋转入口）。
Future<void>  setOrientationMode({required String sessionId , required OrientationMode mode }) => RustLib.instance.api.crateRustScrcpyApiServiceSetOrientationMode(sessionId: sessionId, mode: mode);

/// 请求会话尽快输出关键帧（IDR）。
Future<void>  requestIdr({required String sessionId }) => RustLib.instance.api.crateRustScrcpyApiServiceRequestIdr(sessionId: sessionId);

/// 获取会话统计快照。
Future<SessionStats>  getSessionStats({required String sessionId }) => RustLib.instance.api.crateRustScrcpyApiServiceGetSessionStats(sessionId: sessionId);

            
            