// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../gh_common/model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            /// 初始化 Rust 侧日志系统。
///
/// 语义：
/// - 仅首次调用生效，后续调用幂等返回；
/// - 推荐在应用启动阶段调用一次。
Future<void>  setupLogger({required LogLevel maxLevel }) => RustLib.instance.api.crateGhApiFlutterApiSetupLogger(maxLevel: maxLevel);

/// 列出 ADB 在线设备。
///
/// 返回值中的 `device_id` 可直接用于创建会话。
Future<List<DeviceInfo>>  listDevices({required String adbPath }) => RustLib.instance.api.crateGhApiFlutterApiListDevices(adbPath: adbPath);

/// 查询单个设备详情（型号、系统版本、分辨率等）。
Future<DeviceInfo>  getDeviceInfo({required String adbPath , required String deviceId }) => RustLib.instance.api.crateGhApiFlutterApiGetDeviceInfo(adbPath: adbPath, deviceId: deviceId);

/// 创建会话（仅注册，不启动）。
///
/// 调用方需继续调用 [`start_session`] 进入运行态。
Future<String>  createSession({required SessionConfig config }) => RustLib.instance.api.crateGhApiFlutterApiCreateSession(config: config);

/// 创建会话（V2：支持渲染模式与解码模式配置）。
Future<String>  createSessionV2({required SessionConfigV2 config }) => RustLib.instance.api.crateGhApiFlutterApiCreateSessionV2(config: config);

/// 启动指定会话。
///
/// 幂等：重复启动同一运行中会话会被忽略。
Future<void>  startSession({required String sessionId }) => RustLib.instance.api.crateGhApiFlutterApiStartSession(sessionId: sessionId);

/// 停止指定会话。
///
/// 停止后会话仍保留，可再次 `start_session`。
Future<void>  stopSession({required String sessionId }) => RustLib.instance.api.crateGhApiFlutterApiStopSession(sessionId: sessionId);

/// 销毁会话并移除会话状态。
///
/// 销毁后该 `session_id` 不可复用。
Future<void>  disposeSession({required String sessionId }) => RustLib.instance.api.crateGhApiFlutterApiDisposeSession(sessionId: sessionId);

/// 发送触摸事件到设备。
Future<void>  sendTouch({required String sessionId , required TouchEvent event }) => RustLib.instance.api.crateGhApiFlutterApiSendTouch(sessionId: sessionId, event: event);

/// 发送按键事件到设备。
Future<void>  sendKey({required String sessionId , required KeyEvent event }) => RustLib.instance.api.crateGhApiFlutterApiSendKey(sessionId: sessionId, event: event);

/// 发送滚轮事件到设备。
Future<void>  sendScroll({required String sessionId , required ScrollEvent event }) => RustLib.instance.api.crateGhApiFlutterApiSendScroll(sessionId: sessionId, event: event);

/// 发送文本输入到设备。
Future<void>  sendText({required String sessionId , required String text }) => RustLib.instance.api.crateGhApiFlutterApiSendText(sessionId: sessionId, text: text);

/// 发送系统语义按键（Home/Back/音量等）。
Future<void>  sendSystemKey({required String sessionId , required SystemKey key }) => RustLib.instance.api.crateGhApiFlutterApiSendSystemKey(sessionId: sessionId, key: key);

/// 设置设备剪贴板。
///
/// `paste=true` 时会触发设备端粘贴动作（由 scrcpy server 能力决定）。
Future<void>  setClipboard({required String sessionId , required String text , required bool paste }) => RustLib.instance.api.crateGhApiFlutterApiSetClipboard(sessionId: sessionId, text: text, paste: paste);

/// 设置会话方向模式。
///
/// 该接口表达“方向意图”，实际生效以 `ResolutionChanged` 事件为准。
Future<void>  setOrientationMode({required String sessionId , required OrientationMode mode }) => RustLib.instance.api.crateGhApiFlutterApiSetOrientationMode(sessionId: sessionId, mode: mode);

/// 请求关键帧（IDR），用于重同步加速恢复。
Future<void>  requestIdr({required String sessionId }) => RustLib.instance.api.crateGhApiFlutterApiRequestIdr(sessionId: sessionId);

/// 查询会话统计快照（FPS、时延、累计帧计数等）。
Future<SessionStats>  getSessionStats({required String sessionId }) => RustLib.instance.api.crateGhApiFlutterApiGetSessionStats(sessionId: sessionId);

/// 订阅会话事件流（替代 Runner -> MethodChannel 事件桥）。
///
/// 说明：
/// - 该接口返回后，Rust 将异步持续向 `sink` 推送 `SessionEvent`；
/// - 调用方取消 Dart 订阅后，Rust 转发线程会自动退出。
Stream<SessionEvent>  subscribeSessionEvents({required String sessionId }) => RustLib.instance.api.crateGhApiFlutterApiSubscribeSessionEvents(sessionId: sessionId);

/// 订阅设备剪贴板事件流（仅 `ClipboardChanged` 文本）。
///
/// 说明：
/// - 与会话主事件流解耦，避免上层为处理剪贴板而阻塞状态链路；
/// - 调用方取消 Dart 订阅后，Rust 转发线程会自动退出。
Stream<String>  subscribeClipboardEvents({required String sessionId }) => RustLib.instance.api.crateGhApiFlutterApiSubscribeClipboardEvents(sessionId: sessionId);

/// 订阅 Rust 日志流（FRB）。
///
/// 说明：
/// - 全局日志总线，不绑定单会话；
/// - 调用方取消 Dart 订阅后，Rust 转发线程会自动退出。
Stream<LogEvent>  subscribeLogs() => RustLib.instance.api.crateGhApiFlutterApiSubscribeLogs();

            
            